---
title: "Exercises"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Exercises}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains a list of exercises.

```{r, echo=FALSE, results='asis'}
s_url_ex <- "https://charlotte-ngs.github.io/asmss2022/ex/"
s_url_nb <- "https://charlotte-ngs.github.io/asmss2022/nb/"
tbl_ex <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                         Date = c("2022-02-28",
                                  "2022-03-07",
                                  "2022-03-14",
                                  "2022-03-21",
                                  "2022-03-28",
                                  "2022-04-04",
                                  "2022-04-11",
                                  "2022-04-25",
                                  "2022-05-02",
                                  "2022-05-23",
                                  "2022-05-23",
                                  "2022-05-23"),
                         Topic = c(
                           paste0("Linear Regression [pdf](", s_url_ex, "asm_ex01.pdf) | [nb](", s_url_nb, "asm_ex01_nb_src.nb.html)",  collapse = ""),
                           paste0("Linear Regression (Part 2) [pdf](", s_url_ex, "asm_ex02.pdf) | [nb](", s_url_nb, "asm_ex02_nb_src.nb.html)",  collapse = ""),
                           paste0("Regression on Dummy Variables [pdf](", s_url_ex, "asm_ex03.pdf) | [nb](", s_url_nb, "asm_ex03_nb_src.nb.html)", collapse = ""),
                           paste0("Overfitting and Plots [pdf](", s_url_ex, "asm_ex04.pdf) | [nb](", s_url_nb, "asm_ex04_nb_src.nb.html)", collapse = ""),
                           paste0("Contrasts and Simulation [pdf](", s_url_ex, "asm_ex05.pdf) | [nb](", s_url_nb, "asm_ex05_nb_src.nb.html)", collapse = ""),
                           paste0("Experimental Verification [pdf](", s_url_ex, "asm_ex06.pdf) | [nb](", s_url_nb, "asm_ex06_nb_src.nb.html)", collapse = ""),
                           paste0("Model Selection [pdf](", s_url_ex, "asm_ex07.pdf) | [nb](", s_url_nb, "asm_ex07_nb_src.nb.html)", collapse = ""),
                           paste0("ANOVA and Random Effects Models [pdf](", s_url_ex, "asm_ex08.pdf) | [nb](", s_url_nb, "asm_ex08_nb_src.nb.html)", collapse = ""),
                           paste0("Sire Model [pdf](", s_url_ex, "asm_ex09.pdf) | [nb](", s_url_nb, "asm_ex09_nb_src.nb.html)", collapse = ""),
                           paste0("Comparison of Sire Model and Animal Model [pdf](", s_url_ex, "asm_ex10.pdf) | [nb](", s_url_nb, "asm_ex10_nb_src.nb.html)", collapse = ""),
                           paste0("Genomic Prediction [pdf](", s_url_ex, "asm_ex11.pdf) | [nb](", s_url_nb, "asm_ex11_nb_src.nb.html)", collapse = ""),
                           paste0("Test Exam [pdf](", s_url_ex, "asm_test_exam.pdf)", collapse = "")
                         ))
knitr::kable(tbl_ex)
```

