---
title: "Additional Material"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional Material}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains additional material like links to slides, video recordings, ohp pictures, and more ...


## Slides
```{r tbl-sl, echo=FALSE, message=FALSE, warning=FALSE}
s_sl_url <- "https://charlotte-ngs.github.io/asmss2022/sl/"
tbl_sl <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                         Date = c("2022-02-21",
                                  "2022-02-28",
                                  "2022-02-28",
                                  "2022-03-07",
                                  "2022-03-14",
                                  "2022-03-21",
                                  "2022-03-28",
                                  "2022-04-04",
                                  "2022-04-25",
                                  "2022-05-02",
                                  "2022-05-09",
                                  "2022-05-16"),
                         Topic = c(
                           paste0("[Introduction](", s_sl_url, "asm-w01-v01-intro.pdf)", collapse = ""),
                           paste0("[Linear Regression](", s_sl_url, "l02_regr.pdf)", collapse = ""),
                           paste0("[Linear Regression (Part 2)](", s_sl_url, "l02_regr_part2.pdf)", collapse = ""),
                           paste0("Fixed Linear Effects Model [org](", s_sl_url, "l03_flem.pdf) | [with notes](", s_sl_url, "l03_flem_with_notes.pdf)", collapse = ""),
                           paste0("[Regression on Dummy Variables](", s_sl_url, "l04_regdvar.pdf)", collapse = ""),
                           paste0("[Contrasts](", s_sl_url, "l05_contrasts.pdf)", collapse = ""),
                           paste0("[Contrasts, Plots and Simulation](", s_sl_url, "l06_con_plot_sim.pdf)", collapse = ""),
                           paste0("[Model Selection](", s_sl_url, "l07_model_selection.pdf)", collapse = ""),
                           paste0("[Repeated Measures ANOVA and Random Effects Models](", s_sl_url, "l08_anova_rem.pdf)", collapse = ""),
                           paste0("[Linear Mixed Effects Models](", s_sl_url, "l09_mlem.pdf)", collapse = ""),
                           paste0("[Pedigree BLUP Sire Model](", s_sl_url, "l10_pblup_sire_model.pdf)", collapse = ""),
                           paste0("[Animal Model and Genomic BLUP](", s_sl_url, "l12_animal_model_gblup.pdf)", collapse = "")
                         ))
knitr::kable(tbl_sl)
```

## Videos
```{r tbl-video, echo=FALSE, message=FALSE, warning=FALSE}
tbl_video <- tibble::tibble(Nr = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
                            Date = c("2022-02-21",
                                     "2022-02-28",
                                     "2022-03-07",
                                     "2022-03-14",
                                     "2022-03-21",
                                     "2022-03-28",
                                     "2022-04-04",
                                     "2022-04-11",
                                     "2022-04-25",
                                     "2022-05-02",
                                     "2022-05-09",
                                     "2022-05-16"),
                            Topic = c(
                              "[Introduction](https://youtu.be/9XdsxWiXU90)",
                              "[Linear Regression Analysis](https://youtu.be/RABkYT673HY)",
                              "[Discrete Predictor Variables](https://youtu.be/r8RVceub6Dg)",
                              "[Regression on Dummy Variables](https://youtu.be/ny9cUQAL0wU)",
                              "[Generalized Inverses and Estimable Functions](https://youtu.be/OIrArr82MkA)",
                              "[Contrasts in R, Plotting and Simulation](https://youtu.be/cKJRerCMVFc)",
                              "[Model Selection](https://youtu.be/Kmu0aUJktkU)",
                              "[Model Selection II](https://youtu.be/o2qWmcHdA3A)",
                              "[Repeated Measures ANOVA and Random Effects Models](https://youtu.be/VNnmVci5gRw)",
                              "[Random Effects and Mixed Effects](https://youtu.be/OW9iAUecAEA)",
                              "Linear Mixed Effects Models [Part 1](https://youtu.be/KF0c8A9AavY) | [Part 2](https://youtu.be/WjZAKvt7NGU)",
                              "[Animal Model and Genomic BLUP](https://youtu.be/3oUNGW5flks)"
                            ))
knitr::kable(tbl_video)
```


## OHP
```{r tbl-ohp, echo=FALSE, message=FALSE, warning=FALSE}
s_ohp_url <- "https://charlotte-ngs.github.io/asmss2022/ohp/"
tbl_ohp <- tibble::tibble(Nr = c(1, 2),
                          Date = c("2022-02-21",
                                   "2022-02-28"),
                          Topic = c(
                            paste0("[Introduction](", s_ohp_url, "20220221_ohp_pictures.pdf)", collapse = ""),
                            paste0("[Linear Regression Analysis](", s_ohp_url, "20220228_ohp_pictures.pdf)")
                          ))
knitr::kable(tbl_ohp)
```

