---
title: "R Notebook"
output: html_notebook
---

## Data

```{r}
s_ex03p03_data_path <- "https://charlotte-ngs.github.io/asmss2022/data/asm_bw_flem.csv"
s_ex03p03_data_path <- file.path(here::here(), "docs", "data", "asm_bw_flem.csv")
tbl_ex03p03_data <- readr::read_csv(file = s_ex03p03_data_path)
```

## Contrasts

These results are consistent with the results obtained by `lm()`. If we wanted to see what type of estimable functions are used by the `lm()` function, it can be shown using the function `contrasts()`. For our example with the Breed, we obtain the contrast matrix by 

```{r}
contrasts(as.factor(tbl_ex03p03_data$Breed))
```

```{r}
model.matrix(lm(`Body Weight`~Breed, data = tbl_ex03p03_data))
```


## Example from Video https://youtu.be/eVSIDf5w1_I

```{r}
data("OrchardSprays")
str(OrchardSprays)
```

Plot

```{r}
plot(decrease ~ treatment, data = OrchardSprays)
```


## Resources

https://www.r-bloggers.com/2015/01/using-and-interpreting-different-contrasts-in-linear-models-in-r/
https://rcompanion.org/rcompanion/h_01.html
https://bookdown.org/pingapang9/linear_models_bookdown/chap-contrasts.html

https://youtu.be/eVSIDf5w1_I
