---
title: Applied Statistical Methods - `r tools::toTitleCase(params$doctype)` 3
author: Peter von Rohr
date: 2022-03-12
output:
  bookdown::pdf_document2:
    toc: false
    number_sections: false
    keep_md: false
    keep_tex: false
header-includes:
 \usepackage{longtable}
 \usepackage{float}
params:
  doctype:
    label: 'Document Type'
    value: 'solution'
    choices: ['exercise', 'solution', 'notebook']
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r ex03p01-setup, echo=FALSE}
s_ex03p01_data_path <- "https://charlotte-ngs.github.io/asmss2022/data/asm_flem_genomic_data.csv"
```

## Problem 1: Linear Regression on Genomic Information
Use the following dataset which is also given in: 

`r  s_ex03p01_data_path`

to estimate marker effects for the single loci using a linear regression model.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
tbl_ex03p01_data <- readr::read_csv(file = s_ex03p01_data_path)
knitr::kable(tbl_ex03p01_data,
             booktabs = TRUE,
             longtable = FALSE,
             escape = FALSE)
```


<!-- your-solution-start
### Your Solution

---  your-solution-end -->


<!-- master-solution-start -->

### Solution

<!-- master-solution-end -->


## Problem 2

<!-- your-solution-start
### Your Solution

---  your-solution-end -->


<!-- master-solution-start -->

### Solution

<!-- master-solution-end -->


## Problem 3

<!-- your-solution-start
### Your Solution

---  your-solution-end -->


<!-- master-solution-start -->

### Solution

<!-- master-solution-end -->
 
