---
title: Linear Mixed Effects Models
author: Peter von Rohr
date: "`r Sys.Date()`"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## Dataset

```{r, echo=FALSE}
s_bw_breed_rep_obs_path <- "https://charlotte-ngs.github.io/asmss2022/data/asm_bw_breed_rep_obs.csv"
tbl_rep_obs_breed <- readr::read_csv(file = s_bw_breed_rep_obs_path)
tbl_rep_obs_breed <- dplyr::select(tbl_rep_obs_breed, Animal, `Body Weight`, Breed)
tbl_rep_obs_breed$Animal <- as.factor(tbl_rep_obs_breed$Animal)
tbl_rep_obs_no_breed <- dplyr::select(tbl_rep_obs_breed, Animal, `Body Weight`)
knitr::kable(tbl_rep_obs_no_breed,
             booktabs = TRUE,
             longtable = TRUE)

```


## ANOVA

```{r, echo=TRUE}
aov_bw_no_breed_rep <- aov(`Body Weight` ~ Error(Animal), data = tbl_rep_obs_no_breed)
summary(aov_bw_no_breed_rep)
```


## lme4

```{r, echo=TRUE}
lme_bw_no_breed_rep <- lme4::lmer(`Body Weight` ~ (1|Animal), 
                                  data = tbl_rep_obs_no_breed)
summary(lme_bw_no_breed_rep)
```


## With Breed

```{r}
knitr::kable(tbl_rep_obs_breed,
             booktabs = TRUE,
             longtable = TRUE)
```

## ANOVA

```{r, echo=TRUE}
aov_bw_breed_rep <- aov(`Body Weight` ~ Breed + 
                          Error(Animal), 
                           data = tbl_rep_obs_breed)
summary(aov_bw_breed_rep)
```


## lme4

```{r, echo=TRUE}
lme_bw_breed_rep <- lme4::lmer(`Body Weight` ~ Breed + 
                                 (1|Animal), 
                                  data = tbl_rep_obs_breed)
summary(lme_bw_breed_rep)
```
